<a href="https://colab.research.google.com/github/aspiringmind/Data-Science-and-ML-projects/blob/master/REVIEW_NLP_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NATURAL LANGUAGE PROCESSING PROJECT

Each observation in this dataset is a review of a particular business by a particular user.

The "stars" column is the number of stars (1 through 5) assigned by the reviewer to the business.

The "cool" column is the number of "cool" votes this review received from other Yelp users.

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns
import cufflinks as cf
import plotly.graph_objects as go
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


**IMPORTING NLP**

In [0]:
import nltk
nltk.download_shell()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> l

Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.....

In [0]:
from nltk.corpus import stopwords

In [0]:
stopwords.words("english")

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [0]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [0]:
from google.colab import files
up = files.upload()

Saving rating.csv to rating.csv


In [0]:
import io
csv= pd.read_csv(io.BytesIO(up["rating.csv"]))

In [0]:
df = pd.DataFrame(csv)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   business_id  10000 non-null  object
 1   date         10000 non-null  object
 2   review_id    10000 non-null  object
 3   stars        10000 non-null  int64 
 4   text         10000 non-null  object
 5   type         10000 non-null  object
 6   user_id      10000 non-null  object
 7   cool         10000 non-null  int64 
 8   useful       10000 non-null  int64 
 9   funny        10000 non-null  int64 
dtypes: int64(4), object(6)
memory usage: 781.4+ KB


In [0]:
df.describe()

stars          cool        useful         funny
count  10000.000000  10000.000000  10000.000000  10000.000000
mean       3.777500      0.876800      1.409300      0.701300
std        1.214636      2.067861      2.336647      1.907942
min        1.000000      0.000000      0.000000      0.000000
25%        3.000000      0.000000      0.000000      0.000000
50%        4.000000      0.000000      1.000000      0.000000
75%        5.000000      1.000000      2.000000      1.000000
max        5.000000     77.000000     76.000000     57.000000

**CREATING A COLUMN TO FIND TEXT LENGTH**

In [0]:
df["text_len"]= df["text"].apply(len)

In [0]:
df.head(3)

business_id        date  ... funny  text_len
0  9yKzy9PApeiPPOUJEtnvkg  26-01-2011  ...     0       889
1  ZRJwVLyzEJq1VAihDhYiow  27-07-2011  ...     0      1345
2  6oRAC4uyJCsJl1X0WZpVSA  14-06-2012  ...     0        76

[3 rows x 11 columns]

**TRACING The MAXIMUM LENGTH OF A TEXT ITS INDEX AND THE MESSAGE**

In [0]:
df["text_len"].max()

4997

In [0]:
df[["text_len"]].idxmax()

text_len    55
dtype: int64

In [0]:
df.iloc[55]

business_id                               FCcFT610nQBVcRdY-devQA
date                                                  14-01-2012
review_id                                 6jRs2P6zTYMn36fVnCu1Zw
stars                                                          4
text           In our continuing quest to identify cool, loca...
type                                                      review
user_id                                   40aklZ2SQPKnlTPZdvAqww
cool                                                           0
useful                                                         1
funny                                                          0
text_len                                                    4997
Name: 55, dtype: object

In [0]:
lng_mess=df[df["text_len"]==df["text_len"].max()]["text"].iloc[0].split("\n\n")
lng_mess

['In our continuing quest to identify cool, locally owned places to eat and/or drink, Caroline and I auditioned Vintage 95 last night. ',
 "Before I go further, understand that whenever I go out for eats or drinks, I have  in  mind a Platonic Ideal of the Bar/Pub/Eatery I most want to frequent. I'm on a constant quest to find that  Ideal expressed in Real Life. ",
 "Vintage 95 isn't quite there, but it's damn close. If I ever give something Five Stars, you'll know it has pegged my Platonic Ideal. Anyway...",
 'The plan last night was for drinks. No plans for food, just Adult Beverages and warm conversation. But it turned into more.',
 "The location in downtown Chandler is terrific for us. The owners have created a very fine visual experience - leather, stone, dark woods, good lighting. And they don't have the music turned up so loud that you CANNOT HAVE A CONVERSATION. This is one of my pet peeves. If I want to stare at people move their mouths while enduring an aural assault, I'll sta

**WRITING A FUNCTION TO CLEAN MY TEXT FROM STOPWORDS AND PUNCTUATIONS**

In [0]:
def clean(mess):
  mess= mess.split(" ")
  mess = [i for i in mess if i not in ((string.punctuation)and(stopwords.words("english")))]
  textmessage= " ".join(mess)
  return textmessage

In [0]:
#AttributeError: 'Series' object has no attribute 'split' ---->cleandata = df["text"].split(" ") 
df["clean_text"]=df["text"].apply(lambda x :clean(x))

In [0]:
df.head(4)

business_id  ...                                         clean_text
0  9yKzy9PApeiPPOUJEtnvkg  ...  My wife took birthday breakfast excellent.  Th...
1  ZRJwVLyzEJq1VAihDhYiow  ...  I idea people give bad reviews place. It goes ...
2  6oRAC4uyJCsJl1X0WZpVSA  ...  love gyro plate. Rice good I also dig candy se...
3  _1QQZuf4zZOyFCvXc0o6Vg  ...  Rosie, Dakota, I LOVE Chaparral Dog Park!!! It...

[4 rows x 12 columns]

**FINDING LENGTH OF A NORMAL TEXT STRING AND CLEAN TEXT STRING**

len(string)

In [0]:
len(df["clean_text"].iloc[55])

3653

In [0]:
len(df["text"].iloc[55])

4997

**COUNT VECTORISER**

It reduces the frequency of the repeated words

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
x= df[(df.clean_text==1)|(df.stars==5)]["clean_text"].values
y= df[(df.clean_text==1)|(df.stars==5)]["stars"].values
cv = CountVectorizer()

In [0]:
x= cv.fit_transform(x)

**TRAIN AND TEST SPLIT**

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

**INTRODUCING A CLASSIFIER**

Naive Bayes classifier for multinomial models

The multinomial Naive Bayes classifier is suitable for classification with discrete features (e.g., word counts for text classification). The multinomial distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

In [0]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train,y_train)



MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

**PREDICTION**

In [0]:
predict = nb.predict(X_test)

**CLASSIFICATION MATRIX REPORT**

In [0]:
print("Classification report")
print(classification_report(y_test,predict))

Classification report
              precision    recall  f1-score   support

           5       1.00      1.00      1.00      1002

    accuracy                           1.00      1002
   macro avg       1.00      1.00      1.00      1002
weighted avg       1.00      1.00      1.00      1002



**USING TFIDF TRANSFORMER**

The goal of using tf-idf instead of the raw frequencies of occurrence of a token in a given document is to scale down the impact of tokens that occur very frequently in a given corpus and less informative than features that occur in a small fraction of the training corpus.

In [0]:
from sklearn.feature_extraction.text import TfidfTransformer

**PIPELINE CREATION**

Pass the classifiers and transformers with object has tuples
The pipeline can be used as any other estimator and avoids leaking the test set into the train set

In [0]:
from sklearn.pipeline import Pipeline

In [0]:
pipe= Pipeline(
    [
     ("cv",CountVectorizer()),
     ("idf",TfidfTransformer()),
     ("nb",MultinomialNB())
     ]
)


In [0]:
newdata = df[(df.stars==1)|(df.stars==5)] #|(df.stars==3)]
x= newdata["clean_text"].values
y= newdata["stars"].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [0]:
pipe.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('cv',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [0]:
predict = pipe.predict(X_test)

In [0]:
print("Classification report")
print(classification_report(y_test,predict))

Classification report
              precision    recall  f1-score   support

           1       0.88      0.69      0.77       228
           5       0.93      0.98      0.95       998

    accuracy                           0.92      1226
   macro avg       0.91      0.84      0.86      1226
weighted avg       0.92      0.92      0.92      1226



In [0]:
pipe.predict(["fantastic"])

array([5])

In [0]:
pipe.predict(["worst"])

array([1])

**LOOKING FOR THE BEST AND THE WORST - WITHOUT TFIDF**

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=101)

In [0]:
pipe= Pipeline(
    [
     ("cv",CountVectorizer()),
     ("nb",MultinomialNB())
     ]
)
pipe.fit(X_train,y_train)


Pipeline(memory=None,
         steps=[('cv',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [0]:
predict = pipe.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix,classification_report
print("Confusion matrix")
print(confusion_matrix(y_test,predict))

Confusion matrix
[[158  70]
 [ 22 976]]


In [0]:
print("Classification report")
print(classification_report(y_test,predict))

Classification report
              precision    recall  f1-score   support

           1       0.88      0.69      0.77       228
           5       0.93      0.98      0.95       998

    accuracy                           0.92      1226
   macro avg       0.91      0.84      0.86      1226
weighted avg       0.92      0.92      0.92      1226



In [0]:
pipe.predict(["it is horrible"])

array([1])

In [0]:
pipe.predict(["it is worthy"])

array([5])

In [0]:
pipe.predict(["it is irritating"])

array([1])

****

In [0]:
y_test.shape

(1226,)

In [0]:
predict.shape

(1226,)

In [0]:
real = pd.Series(y_test)

In [0]:
result = pd.DataFrame(predict)

In [0]:
evaluate = pd.concat([real,result],axis=1)

In [0]:
evaluate.columns = ["real","predicted"]

**Comparison chat**

In [0]:
evaluate.head(10)

real  predicted
0     5          5
1     1          1
2     5          5
3     5          5
4     1          5
5     5          5
6     5          5
7     5          5
8     5          5
9     5          5

**FINDING THE BEST AND THE WORST USING SGDCLASSIFIER

In [0]:
from sklearn.linear_model import SGDClassifier

sgd = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42, max_iter=5, tol=None)),
               ])
sgd.fit(X_train, y_train)


Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=Non...
                ('clf',
                 SGDClassifier(alpha=0.001, average=False, class_weight=None,
                               early_stopping=False, epsilon=0.1, eta0=0.0,
                               fit_intercept=True, l1_ratio=0.15,
                               learning_rate='optimal', loss='hinge',
                      

In [0]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           1       0.88      0.69      0.77       228
           5       0.93      0.98      0.95       998

    accuracy                           0.92      1226
   macro avg       0.91      0.84      0.86      1226
weighted avg       0.92      0.92      0.92      1226



# Finally got a model with 92 percantage accuracy to detect whether the review is the best or the worst